[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/create-preference"
  to   = "/.netlify/functions/create-preference"
  status = 200
  force = true
